USE LOPO
GO
CREATE TABLE USUARIO
(
	ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL,
	TELEFONO INT NOT NULL
)
GO
CREATE TABLE BLOQUE
(
	NRO_BLOQUE INT IDENTITY(1,1) PRIMARY KEY,
	ENUNCIADO VARCHAR(100) NOT NULL,
	RESPUESTA1 VARCHAR(100) NOT NULL,
	RESPUESTA2 VARCHAR(100) NOT NULL,
	RESPUESTA3 VARCHAR(100) NOT NULL,
	CORRECTA VARCHAR(100) NOT NULL
)
GO
CREATE PROCEDURE AGREGAR_BLOQUE
	@ENUNCIADO VARCHAR(100),
	@RESPUESTA1 VARCHAR(100),
	@RESPUESTA2 VARCHAR(100),
	@RESPUESTA3 VARCHAR(100),
	@CORRECTA VARCHAR(100)
	AS
	SET NOCOUNT ON
	BEGIN
	IF EXISTS ( SELECT 1 FROM BLOQUE WHERE ENUNCIADO = @ENUNCIADO )
		BEGIN 
			THROW 50001, ' Ya existe este enunciado ',1;
		END
	INSERT INTO  BLOQUE(ENUNCIADO,RESPUESTA1,RESPUESTA2,RESPUESTA3,CORRECTA)
		VALUES(@ENUNCIADO,@RESPUESTA1,@RESPUESTA2,@RESPUESTA3,@CORRECTA)
	END
GO
CREATE PROCEDURE ELIMINAR_BLOQUE
	@NRO_BLOQUE INT
	AS
	SET NOCOUNT ON
	BEGIN
	IF NOT EXISTS( SELECT 1 FROM BLOQUE WHERE NRO_BLOQUE = @NRO_BLOQUE)
		BEGIN
			THROW 50001, ' Este numero de bloque no existe ',1;
		END
	DELETE FROM BLOQUE WHERE NRO_BLOQUE = @NRO_BLOQUE
	END
GO
CREATE PROCEDURE OBTENERBLOQUES
	AS
	SET NOCOUNT ON
	BEGIN
		SELECT * FROM BLOQUE
	END
GO
CREATE PROCEDURE AGREGAR_USUARIO
	@NOMBRE VARCHAR(100),
	@TELEFONO INT
	AS SET NOCOUNT ON
	BEGIN
	IF EXISTS( SELECT 1 FROM USUARIO WHERE TELEFONO = @TELEFONO)
		BEGIN
			THROW 50001, 'Este usuario  ya existe ',1;
		END
	INSERT INTO USUARIO(NOMBRE,TELEFONO) 
		VALUES(@NOMBRE, @TELEFONO)
	END
GO
CREATE PROCEDURE ELIMINAR_USUARIO
	@ID_USUARIO INT
	AS SET NOCOUNT ON
	BEGIN
	IF NOT EXISTS( SELECT 1 FROM USUARIO WHERE ID_USUARIO = @ID_USUARIO)
		BEGIN
		 THROW 50001,' Este usuario no existe ', 1;
		END
	DELETE FROM USUARIO WHERE ID_USUARIO = @ID_USUARIO
	END
GO
CREATE PROCEDURE OBTENER_USUARIOS
	AS
	SET NOCOUNT ON
	BEGIN
	SELECT * FROM USUARIO
	END
GO